version: '3.8'

x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:latest
    ports:
      - "2358:2358"
    volumes:
      - judge0_tmp:/box
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - db
      - redis
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
      - ENABLE_WAIT_RESULT=true
      - ENABLE_COMPILER_OPTIONS=true
      - ENABLE_COMMAND_LINE_ARGUMENTS=true
      - ENABLE_SUBMISSION_DELETE=true
      - ENABLE_CALLBACKS=true
      - ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=false
      - ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    volumes:
      - judge0_tmp:/box
      - /var/run/docker.sock:/var/run/docker.sock
    <<: *default-logging
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
      - RAILS_ENV=production
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "${REDIS_PASSWORD}"'
    ]
    volumes:
      - redis_data:/data
    <<: *default-logging
    restart: always

volumes:
  postgres_data:
  redis_data:
  judge0_tmp:
